/**
 * Alle teksten van Groos Beheer (spec 08 §6.2). Alleen Nederlands, je-vorm,
 * buiten messages/ en buiten de spiegelcontrole. Plaatshouders staan tussen
 * accolades en worden met fill() ingevuld.
 */
export const S = {
  app: {
    name: "Groos Beheer",
    titleTemplate: "%s · Groos Beheer",
    skipLink: "Naar de inhoud",
    loading: "Even geduld, de gegevens worden geladen.",
    viewSite: "Bekijk website",
    signOut: "Uitloggen",
    signOutEverywhere: "Overal uitloggen",
    back: "Terug",
    roleOwner: "Eigenaar",
    roleRecruiter: "Medewerker",
    short: "Beheer",
  },
  nav: {
    label: "Hoofdmenu",
    tabBarLabel: "Snelmenu",
    dashboard: "Overzicht",
    vacancies: "Vacatures",
    applications: "Sollicitaties",
    requests: "Aanvragen",
    requestsLong: "Personeelsaanvragen",
    messages: "Berichten",
    more: "Meer",
    newBadge: "{aantal} nieuw",
  },
  common: {
    save: "Opslaan",
    cancel: "Annuleren",
    close: "Sluiten",
    confirm: "Bevestigen",
    edit: "Bewerken",
    delete: "Verwijderen",
    search: "Zoeken",
    filters: "Filters",
    clearFilters: "Filters wissen",
    apply: "Toepassen",
    actions: "Acties",
    previous: "Vorige",
    next: "Volgende",
    pageOf: "Pagina {pagina} van {totaal}",
    viewAll: "Alle {aantal} bekijken",
    yes: "Ja",
    no: "Nee",
    notFilled: "Niet ingevuld",
    nobody: "Niemand",
    me: "Ik",
    assignToMe: "Aan mij toewijzen",
    copied: "Gekopieerd",
    saving: "Bezig met opslaan",
    requiredForPublish: "nodig om te publiceren",
    optional: "optioneel",
    all: "Alle",
    pagination: "Paginering",
  },
  auth: {
    login: {
      metaTitle: "Inloggen",
      title: "Inloggen bij Groos Beheer",
      intro: "Log in met je e-mailadres en wachtwoord. Daarna vragen wij de code uit je authenticator-app.",
      email: "E-mailadres",
      password: "Wachtwoord",
      showPassword: "Wachtwoord tonen",
      hidePassword: "Wachtwoord verbergen",
      submit: "Inloggen",
      forgot: "Wachtwoord vergeten",
    },
    mfa: {
      metaTitle: "Code bevestigen",
      title: "Bevestig dat jij het bent",
      intro: "Open de authenticator-app op je telefoon. Vul de zes cijfers in die bij Groos Beheer staan.",
      code: "Code uit je authenticator-app",
      codeHint: "De code verandert elke 30 seconden. Plakken mag ook.",
      submit: "Code bevestigen",
      lostPhone: "Ben je je telefoon kwijt? Vraag de technisch beheerder om je koppeling te resetten. Daarna koppel je de app opnieuw.",
      otherAccount: "Ander account",
    },
    enroll: {
      metaTitle: "App koppelen",
      title: "Koppel je authenticator-app",
      intro: "Groos Beheer vraagt bij elke keer inloggen een code uit een app op je telefoon. Zo komt niemand met alleen je wachtwoord bij de gegevens van kandidaten.",
      step1: "Installeer een authenticator-app, zoals Google Authenticator, Microsoft Authenticator of 1Password.",
      step2: "Tik op Koppeling starten en scan de QR-code met die app.",
      step3: "Vul de code van zes cijfers in die de app daarna toont.",
      start: "Koppeling starten",
      qrAlt: "QR-code om Groos Beheer aan je authenticator-app te koppelen",
      manualLabel: "Lukt scannen niet? Vul deze sleutel dan met de hand in de app in.",
      copySecret: "Sleutel kopiëren",
      submit: "Code bevestigen",
      restart: "Opnieuw beginnen",
    },
    forgot: {
      metaTitle: "Wachtwoord vergeten",
      title: "Wachtwoord vergeten",
      intro: "Vul het e-mailadres in waarmee je inlogt. Je krijgt dan een link om een nieuw wachtwoord te kiezen.",
      submit: "Herstelmail sturen",
      sent: "Is dit adres bij Groos Beheer bekend, dan staat er binnen een paar minuten een e-mail in je inbox. De link in die e-mail werkt één keer.",
      backToLogin: "Terug naar inloggen",
    },
    setPassword: {
      metaTitle: "Nieuw wachtwoord",
      title: "Kies een nieuw wachtwoord",
      intro: "Kies een wachtwoord van minimaal 12 tekens dat je nergens anders gebruikt. Een wachtwoordkluis helpt je het te onthouden.",
      password: "Nieuw wachtwoord",
      passwordConfirm: "Herhaal het wachtwoord",
      submit: "Wachtwoord opslaan",
    },
    noAccess: {
      title: "Geen toegang",
      body: "Dit account heeft geen toegang tot Groos Beheer. Neem contact op met een eigenaar als je denkt dat dit niet klopt.",
    },
    notices: {
      uitgelogd: "Je bent uitgelogd.",
      "link-verlopen": "Deze link is verlopen of al gebruikt. Vraag een nieuwe herstelmail aan.",
      "wachtwoord-gewijzigd": "Je nieuwe wachtwoord is opgeslagen. Log opnieuw in.",
      "sessie-verlopen": "Je sessie is verlopen. Log opnieuw in om verder te gaan.",
    },
    errors: {
      invalidCredentials: "Het e-mailadres of het wachtwoord klopt niet. Probeer het opnieuw of stel een nieuw wachtwoord in.",
      invalidCode: "Deze code klopt niet of is verlopen. Open je authenticator-app en vul de nieuwste code in.",
      tooManyAttempts: "Je hebt te vaak geprobeerd in te loggen. Wacht een paar minuten en probeer het daarna opnieuw.",
      deactivated: "Dit account heeft geen toegang meer tot het beheer. Neem contact op met een eigenaar.",
      passwordTooShort: "Kies een wachtwoord van minimaal 12 tekens.",
      passwordsDiffer: "De twee wachtwoorden zijn niet hetzelfde. Typ ze opnieuw.",
      passwordWeak: "Dit wachtwoord is te makkelijk te raden of is eerder gelekt. Kies een ander wachtwoord.",
      passwordSame: "Dit is je huidige wachtwoord. Kies een nieuw wachtwoord.",
      bot: "Onze beveiliging heeft dit verzoek tegengehouden. Probeer het over een paar minuten opnieuw.",
      generic: "Er ging iets mis bij het inloggen. Controleer je internetverbinding en probeer het opnieuw.",
    },
  },
  dashboard: {
    metaTitle: "Overzicht",
    greeting: { morning: "Goedemorgen, {naam}", afternoon: "Goedemiddag, {naam}", evening: "Goedenavond, {naam}" },
    newVacancy: "Nieuwe vacature",
    tiles: {
      applicationsNew: "Nieuwe sollicitaties",
      requestsOpen: "Open aanvragen",
      messagesNew: "Nieuwe berichten",
      vacanciesOnline: "Vacatures online",
      closingSoon: "Sluiten binnen 7 dagen",
    },
    todo: {
      title: "Vandaag te doen",
      staleNew: "Nog niet opgepakt",
      staleNewItem: "{naam} wacht sinds {datum} op een reactie.",
      nearAutoClose: "Bijna automatisch afgesloten",
      nearAutoCloseItem: "{naam} heeft al 8 weken geen contact gehad. Op {datum} sluit Groos Beheer deze sollicitatie automatisch af.",
      requestsNew: "Nieuwe aanvragen",
      requestsNewItem: "{bedrijf} vraagt {aantal} mensen aan.",
      closingSoon: "Sluiten binnenkort",
      closingSoonItem: "{titel} sluit op {datum}.",
      scheduledToday: "Vandaag gepland",
      scheduledTodayItem: "{titel} gaat vandaag om {tijd} online.",
      scheduledInvalidItem: "{titel} staat ingepland, maar er ontbreken nog verplichte velden. Zonder die velden gaat hij niet online.",
      emailFailed: "E-mail niet aangekomen",
      emailFailedItem: "Een e-mail over {referentie} is niet aangekomen. Bel of app de ontvanger.",
    },
    recent: "Recente activiteit",
  },
  activity: {
    note: "{naam} schreef een notitie",
    status_change: "{naam} zette de status op {status}",
    call: "{naam} startte een belactie",
    whatsapp: "{naam} opende WhatsApp",
    email_sent: "{naam} opende een e-mail",
    cv_viewed: "{naam} bekeek het cv",
    assigned: "{naam} wees dit toe aan {toegewezen}",
    consent_recorded: "{naam} legde toestemming vast",
    auto_closed: "Automatisch afgesloten na 12 weken zonder contact",
    system: "Groos Beheer",
    about: "over {onderdeel}",
  },
  vacancies: {
    metaTitle: "Vacatures",
    title: "Vacatures",
    newTitle: "Nieuwe vacature",
    tabs: { online: "Online", gepland: "Gepland", concepten: "Concepten", gesloten: "Gesloten", archief: "Archief", alle: "Alle" },
    tabsLabel: "Vacatures per status",
    searchLabel: "Zoek op titel of vacaturenummer",
    searchPlaceholder: "Bijvoorbeeld glazenwasser of 1042",
    filterOccupation: "Beroep",
    filterContact: "Contactpersoon",
    filterFlag: "Vlag",
    sortLabel: "Sorteren op",
    sort: { bewerkt: "Laatst bewerkt", sluitdatum: "Sluitdatum", nummer: "Vacaturenummer" },
    caption: "Vacatures met status, sluitdatum en aantal sollicitaties",
    columns: {
      title: "Titel", occupation: "Beroep", city: "Plaats", status: "Status", applications: "Sollicitaties",
      onlineSince: "Online sinds", closes: "Sluitdatum", contact: "Contactpersoon", updated: "Laatst bewerkt", actions: "Acties",
    },
    number: "Vacature {nummer}",
    flags: { featured: "Uitgelicht", urgent: "Spoed" },
    form: {
      toc: "Op deze pagina",
      blocks: {
        basis: { title: "Basis", description: "Wat voor werk het is en waar het is." },
        tekst: { title: "Tekst", description: "Deze tekst staat op de vacaturepagina. Schrijf in de je-vorm en houd het kort." },
        voorwaarden: { title: "Arbeidsvoorwaarden", description: "Uren, werktijden en het bruto uurloon." },
        eisen: { title: "Eisen", description: "Noem alleen wat echt nodig is voor het werk." },
        publicatie: { title: "Publicatie", description: "Wie de contactpersoon is en hoe lang de vacature online staat." },
        vindbaarheid: { title: "Vindbaarheid", description: "Optioneel. Laat leeg, dan maken wij titel en omschrijving voor Google zelf." },
      },
      fields: {
        occupation_slug: { label: "Beroep", hint: "Kies het beroep waar deze vacature bij hoort. Dat bepaalt waar de vacature op de site verschijnt." },
        title: { label: "Functietitel", hint: "Schrijf de functie zoals een werkzoekende hem zoekt, bijvoorbeeld Orderpicker vroege dienst. De plaats komt er vanzelf bij." },
        city: { label: "Plaats", hint: "De plaats waar het werk is." },
        postal_code: { label: "Postcode", hint: "Optioneel. Helpt Google om de vacature op de juiste plek te tonen." },
        province: { label: "Provincie", hint: "" },
        location_label: { label: "Locatie zoals bezoekers die zien", hint: "Vul dit alleen in als je liever iets anders toont, zoals Regio Den Haag." },
        positions_count: { label: "Aantal plekken", hint: "Hoeveel mensen zoek je voor deze vacature?" },
        summary: { label: "Korte samenvatting", hint: "Een of twee zinnen voor de vacaturekaart en Google." },
        intro: { label: "Introductie", hint: "Schrijf twee zinnen: wat je gaat doen en voor wie dit werk past." },
        tasks: { label: "Je werkdag", hint: "Eén taak per regel, kort en zonder punt. Minimaal drie taken.", add: "Taak toevoegen" },
        requirements: { label: "Wat je meebrengt", hint: "Noem alleen wat echt nodig is. Een minimumleeftijd? Alleen bij een reden voor veiligheid: werken op hoogte, bouw en sloop, heftruck of reachtruck, nachtwerk of gevaarlijke stoffen.", add: "Eis toevoegen" },
        offer: { label: "Wat je van ons krijgt", hint: "Noem het bruto uurloon en wat je verder echt biedt.", add: "Punt toevoegen" },
        removeItem: "Regel {nummer} verwijderen",
        extra: { label: "Extra informatie", hint: "Optioneel. Bijvoorbeeld over de werkplek of de collega's." },
        contract_type: { label: "Dienstverband", hint: "Bij uitzendwerk kies je Uitzenden." },
        hours_min: { label: "Uren per week, minimaal", hint: "Bij een vast aantal uren vul je twee keer hetzelfde getal in." },
        hours_max: { label: "Uren per week, maximaal", hint: "" },
        shifts: { label: "Werktijden", hint: "Kies alle diensten die voorkomen." },
        salary_min: { label: "Bruto uurloon vanaf", hint: "In euro per uur, bijvoorbeeld 15,50." },
        salary_max: { label: "Bruto uurloon tot", hint: "Bij een vast uurloon vul je twee keer hetzelfde bedrag in." },
        salary_note: { label: "Toelichting bij het loon", hint: "Optioneel. Bijvoorbeeld toeslagen voor avond- en weekendwerk." },
        start_asap: { label: "Per direct beginnen", hint: "Vink dit uit om een startdatum te kiezen." },
        start_date: { label: "Startdatum", hint: "" },
        education_level: { label: "Opleidingsniveau", hint: "Kies Geen opleiding nodig als iedereen kan solliciteren." },
        experience_level: { label: "Ervaring", hint: "" },
        experience_months: { label: "Hoeveel maanden ervaring?", hint: "" },
        required_qualifications: { label: "Vereist", hint: "Diploma's, certificaten en rijbewijzen die nodig zijn." },
        preferred_qualifications: { label: "Mooi meegenomen", hint: "Niet nodig, wel een pré." },
        training_offered: { label: "Opleiding die Groos regelt", hint: "Vink alleen aan wat Groos voor deze vacature echt regelt." },
        min_age_18: { label: "Minimumleeftijd 18 jaar", hint: "Alleen bij een reden voor veiligheid: werken op hoogte, bouw en sloop, heftruck of reachtruck, nachtwerk of gevaarlijke stoffen." },
        min_age_reason: { label: "Reden voor de minimumleeftijd", hint: "Deze reden staat bij de vacature." },
        workplace_language: { label: "Taal op het werk", hint: "Dit veld is niet verplicht. Kies de taal die je op de werkplek nodig hebt." },
        contact_admin_id: { label: "Contactpersoon", hint: "Naam, telefoonnummer en WhatsApp van deze persoon staan bij de vacature." },
        closes_at: { label: "Sluitdatum", hint: "Bij een concept mag je dit leeg laten; de vacature sluit dan 45 dagen na het publiceren. Na deze datum gaat de vacature automatisch offline." },
        publish_at: { label: "Online vanaf", hint: "" },
        is_featured: { label: "Uitlichten", hint: "Uitgelichte vacatures staan bovenaan de lijst en op de homepage." },
        is_urgent: { label: "Spoed", hint: "Toont het label Spoed. Gebruik dit alleen als je echt snel iemand nodig hebt." },
        allow_whatsapp_apply: { label: "Solliciteren via WhatsApp", hint: "Toont een knop waarmee kandidaten de contactpersoon direct een bericht sturen." },
        seo_title: { label: "Titel in Google", hint: "Optioneel, hoogstens 45 tekens; de site zet de merknaam erachter." },
        seo_description: { label: "Omschrijving in Google", hint: "Optioneel, hoogstens 160 tekens." },
      },
      saveDraft: "Opslaan als concept",
      save: "Opslaan",
      publish: "Publiceren",
      publishNow: "Nu publiceren",
      publishChanges: "Wijzigingen publiceren",
      preview: "Voorbeeld bekijken",
      checklistTitle: "Nog nodig om te publiceren",
      warningsTitle: "Controleer dit even",
      history: "Geschiedenis",
      lastEdited: "Laatst bewerkt op {datum} door {naam}",
    },
    actions: {
      menu: "Acties voor {titel}",
      edit: "Bewerken",
      preview: "Voorbeeld bekijken",
      viewOnSite: "Bekijk op website",
      duplicate: "Dupliceren",
      publish: "Publiceren",
      publishNow: "Nu publiceren",
      schedule: "Inplannen",
      reschedule: "Inplanning wijzigen",
      unschedule: "Inplanning annuleren",
      takeOffline: "Offline halen",
      extend: "30 dagen verlengen",
      closeFilled: "Sluiten als vervuld",
      close: "Vacature sluiten",
      reopen: "Heropenen",
      archive: "Archiveren",
      restore: "Terugzetten als concept",
      delete: "Verwijderen",
      copyLink: "Link kopiëren",
      shareWhatsapp: "Delen via WhatsApp",
      shareWhatsappText: "{titel} in {plaats}, bekijk de vacature: {link}",
      viewApplications: "Bekijk sollicitaties",
      feature: "Uitlichten",
      unfeature: "Niet uitlichten",
      urgentOn: "Spoed aanzetten",
      urgentOff: "Spoed uitzetten",
    },
    preview: {
      metaTitle: "Voorbeeld van {titel}",
      bar: "Voorbeeld. Zo ziet de vacature eruit op de website.",
      barDraft: "Voorbeeld. Deze vacature staat nog niet online.",
      back: "Terug naar bewerken",
    },
  },
  applications: {
    metaTitle: "Sollicitaties",
    title: "Sollicitaties",
    tabs: { open: "Open", nieuw: "Nieuw", in_behandeling: "In behandeling", uitgenodigd: "Uitgenodigd", geplaatst: "Geplaatst", afgewezen: "Afgewezen", ingetrokken: "Ingetrokken", alle: "Alle" },
    tabsLabel: "Sollicitaties per status",
    searchLabel: "Zoek op naam, telefoon, e-mail of referentie",
    searchPlaceholder: "Bijvoorbeeld Jansen of 06 12 34 56 78",
    filterVacancy: "Vacature",
    filterRegistration: "Inschrijving zonder vacature",
    filterOccupation: "Beroep",
    filterCv: "Cv",
    cvWith: "Met cv",
    cvWithout: "Zonder cv",
    filterPeriod: "Periode",
    period: { "7": "Laatste 7 dagen", "30": "Laatste 30 dagen", "90": "Laatste 90 dagen" },
    filterAssigned: "Toegewezen aan",
    caption: "Sollicitaties met vacature, status en bewaartermijn",
    columns: {
      name: "Naam", vacancy: "Vacature", city: "Woonplaats", phone: "Telefoon", received: "Ontvangen",
      status: "Status", cv: "Cv", assigned: "Toegewezen aan", retainUntil: "Bewaard tot",
    },
    registration: "Inschrijving",
    hasCv: "Cv aanwezig",
    noCv: "Geen cv",
    detail: {
      metaTitle: "Sollicitatie van {naam}",
      title: "Sollicitatie van {naam}",
      reference: "Referentie {referentie}",
      received: "Ontvangen op {datum}",
      source: "Binnengekomen via {bron}",
      contact: "Contact",
      phone: "Telefoon",
      email: "E-mailadres",
      city: "Woonplaats",
      details: "Gegevens",
      mayWork: "Mag in Nederland werken",
      availableFrom: "Beschikbaar vanaf",
      drivingLicense: "Rijbewijs B",
      occupations: "Interesse in",
      message: "Bericht van de kandidaat",
      language: "Taal van het formulier",
      consent: "Toestemming om een jaar te bewaren (talentpool)",
      consentGiven: "Ja, gegeven op {datum}",
      cv: "Cv",
      statusAndAssign: "Status en toewijzing",
      timeline: "Tijdlijn",
      others: "Andere sollicitaties van deze persoon",
      retention: "Groos Beheer bewaart deze gegevens tot {datum} en verwijdert ze daarna automatisch.",
      whatsappText: "Hoi {voornaam}, je spreekt met {beheerder} van Groos Personeelsdiensten. Je hebt gesolliciteerd op {vacature}. Heb je even tijd om te bellen?",
      whatsappTextRegistration: "Hoi {voornaam}, je spreekt met {beheerder} van Groos Personeelsdiensten. Je hebt je bij ons ingeschreven. Heb je even tijd om te bellen?",
      mailSubject: "Je sollicitatie bij Groos Personeelsdiensten",
      mailSubjectRegistration: "Je inschrijving bij Groos Personeelsdiensten",
    },
    cv: {
      view: "Cv bekijken",
      download: "Cv downloaden",
      meta: "{bestand}, {grootte}",
      opening: "Het cv wordt geopend",
    },
  },
  requests: {
    metaTitle: "Personeelsaanvragen",
    title: "Personeelsaanvragen",
    tabs: { open: "Open", nieuw: "Nieuw", in_behandeling: "In behandeling", offerte: "Offerte verstuurd", gestart: "Gestart", afgerond: "Afgerond", geannuleerd: "Geannuleerd", alle: "Alle" },
    tabsLabel: "Aanvragen per status",
    searchLabel: "Zoek op bedrijf, naam, telefoon of referentie",
    searchPlaceholder: "Bijvoorbeeld Testbedrijf",
    caption: "Personeelsaanvragen met gevraagde beroepen en status",
    columns: {
      company: "Bedrijf", contact: "Contactpersoon", requested: "Gevraagd", headcount: "Aantal", start: "Start",
      workCity: "Werkplaats", received: "Ontvangen", status: "Status", assigned: "Toegewezen aan",
    },
    other: "Anders: {tekst}",
    asap: "Zo snel mogelijk",
    detail: {
      metaTitle: "Aanvraag van {bedrijf}",
      title: "Aanvraag van {bedrijf}",
      request: "Aanvraag",
      occupations: "Gevraagde beroepen",
      headcount: "Aantal mensen",
      start: "Start",
      duration: "Duur",
      hours: "Uren per week",
      workCity: "Werkplaats",
      kvk: "KvK-nummer",
      description: "Toelichting",
      createVacancy: "Vacature maken",
      whatsappText: "Goedendag {naam}, met {beheerder} van Groos Personeelsdiensten over de personeelsaanvraag {referentie}.",
      mailSubject: "Personeelsaanvraag {referentie} bij Groos Personeelsdiensten",
    },
  },
  messages: {
    metaTitle: "Berichten",
    title: "Berichten",
    tabs: { nieuw: "Nieuw", beantwoord: "Beantwoord", gearchiveerd: "Gearchiveerd", spam: "Spam", alle: "Alle" },
    tabsLabel: "Berichten per status",
    searchLabel: "Zoek op naam, e-mail of telefoon",
    filterTopic: "Onderwerp",
    caption: "Berichten via het contactformulier",
    columns: { name: "Naam", topic: "Onderwerp", reachable: "Bereikbaar via", received: "Ontvangen", status: "Status" },
    detail: {
      metaTitle: "Bericht van {naam}",
      title: "Bericht van {naam}",
      callback: "Deze persoon wil graag teruggebeld worden.",
      markAnswered: "Markeren als beantwoord",
      archive: "Archiveren",
      markSpam: "Markeren als spam",
      markNew: "Terugzetten als nieuw",
      reply: "Beantwoorden",
      mailSubject: "Je bericht aan Groos Personeelsdiensten",
      whatsappText: "Goedendag {naam}, met {beheerder} van Groos Personeelsdiensten over het bericht via de website.",
    },
  },
  contact: {
    call: "Bellen",
    whatsapp: "WhatsApp",
    email: "E-mailen",
    status: "Status",
    callAria: "Bel {naam} op {telefoon}",
    whatsappAria: "Stuur {naam} een WhatsApp-bericht",
    emailAria: "Mail {naam}",
  },
  notes: {
    label: "Nieuwe notitie",
    hint: "Schrijf op wat je hebt besproken en wat de volgende stap is.",
    submit: "Notitie toevoegen",
  },
  assign: { label: "Toegewezen aan", submit: "Toewijzen" },
  statusForm: { label: "Status", submit: "Status opslaan" },
  status: {
    vacancy: {
      draft: "Concept", scheduled: "Gepland", published: "Online", expired: "Verlopen", filled: "Vervuld",
      withdrawn: "Ingetrokken", closed_other: "Gesloten", archived: "Gearchiveerd",
    },
    application: { new: "Nieuw", in_progress: "In behandeling", invited: "Uitgenodigd", placed: "Geplaatst", rejected: "Afgewezen", withdrawn: "Ingetrokken" },
    staffRequest: { new: "Nieuw", in_progress: "In behandeling", quote_sent: "Offerte verstuurd", started: "Gestart", completed: "Afgerond", cancelled: "Geannuleerd" },
    message: { new: "Nieuw", answered: "Beantwoord", archived: "Gearchiveerd", spam: "Spam" },
  },
  options: {
    closeReason: { filled: "Vervuld", expired: "Verlopen", withdrawn: "Ingetrokken", other: "Anders" },
    contractType: { temp_agency: "Uitzenden", secondment: "Detachering", recruitment: "In dienst bij de opdrachtgever" },
    shift: { early: "Vroege dienst", day: "Dagdienst", evening: "Avonddienst", night: "Nachtdienst", weekend: "Weekend" },
    education: { none: "Geen opleiding nodig", vmbo: "Vmbo", mbo1: "Mbo 1", mbo2: "Mbo 2", mbo3: "Mbo 3", mbo4: "Mbo 4", havo_vwo: "Havo of vwo", hbo: "Hbo", wo: "Wo" },
    experience: { none: "Geen ervaring nodig", nice_to_have: "Ervaring is mooi meegenomen", required: "Ervaring nodig" },
    qualification: {
      vca_basis: "VCA Basis", vca_vol: "VCA VOL", heftruck: "Heftruckcertificaat", reachtruck: "Reachtruckcertificaat",
      ept: "EPT-certificaat", ipaf: "IPAF (hoogwerker)", vog: "VOG", rijbewijs_b: "Rijbewijs B", rijbewijs_be: "Rijbewijs BE",
      rijbewijs_c: "Rijbewijs C", code_95: "Code 95", ras: "RAS-vakopleiding",
    },
    minAgeReason: {
      work_at_height: "Werken op hoogte", construction_demolition: "Werk op een bouw- of sloopplaats",
      forklift: "Rijden met een heftruck of reachtruck", night_work: "Nachtwerk", hazardous_substances: "Werken met gevaarlijke stoffen",
    },
    duration: { one_day: "Eén dag", days: "Enkele dagen", weeks: "Enkele weken", months: "Enkele maanden", indefinite: "Langdurig", unknown: "Weet ik nog niet" },
    topic: { job_seeker: "Zoekt werk", employer: "Zoekt personeel", callback: "Bel mij terug", other: "Iets anders" },
    source: { website: "Website", whatsapp: "WhatsApp", phone: "Telefoon", walk_in: "Langsgekomen", email: "E-mail", referral: "Via via", job_board: "Vacaturesite", other: "Anders" },
    locale: { nl: "Nederlands", en: "Engels" },
    workplaceLanguage: { nl: "Nederlands", en: "Engels", nl_or_en: "Nederlands of Engels" },
  },
  empty: {
    dashboard: "Er staat vandaag niets open. Nieuwe sollicitaties en aanvragen verschijnen hier automatisch.",
    vacanciesNone: "Je hebt nog geen vacatures. Maak je eerste vacature aan, dan staat hij na het publiceren direct op de website.",
    vacanciesFiltered: "Er zijn geen vacatures die bij deze filters passen. Pas de filters aan of wis ze om alles te zien.",
    vacanciesScheduled: "Er staan geen vacatures ingepland. Kies bij een concept voor Inplannen om hem later automatisch online te zetten.",
    applicationsNone: "Er zijn nog geen sollicitaties binnengekomen. Zodra iemand solliciteert, zie je dat hier en krijg je een e-mail.",
    applicationsNew: "Alle nieuwe sollicitaties zijn opgepakt. Er ligt op dit moment niets op je te wachten.",
    requestsNone: "Aanvragen die opdrachtgevers via de website versturen, komen hier binnen.",
    messagesNone: "Er zijn geen nieuwe berichten. Berichten via het contactformulier verschijnen hier.",
    timeline: "Er zijn nog geen notities. Schrijf hier op wat je hebt besproken, zodat je collega weet hoe het ervoor staat.",
    search: "Niets gevonden voor {zoekterm}. Controleer de spelling of zoek op een telefoonnummer of e-mailadres.",
    others: "Deze persoon heeft niet eerder bij ons gesolliciteerd.",
    noCv: "Er is geen cv meegestuurd. Bel of app de kandidaat om de werkervaring door te nemen.",
    history: "Er is nog niets gebeurd met deze vacature.",
  },
  dialogs: {
    publish: { title: "Vacature publiceren?", body: "De vacature komt direct op de website en is daarna ook te vinden in Google.", confirm: "Publiceren" },
    schedule: { title: "Vacature inplannen?", body: "Kies wanneer de vacature online komt. Tot dat moment kun je hem nog aanpassen.", confirm: "Inplannen", publishAt: "Online vanaf", closesOn: "Sluitdatum" },
    unschedule: { title: "Inplanning annuleren?", body: "De vacature wordt weer een concept en komt niet automatisch online.", confirm: "Inplanning annuleren" },
    takeOffline: { title: "Vacature offline halen?", body: "De vacature verdwijnt van de website en wordt weer een concept. Sollicitaties die al binnen zijn, blijven bewaard.", confirm: "Offline halen" },
    closeFilled: { title: "Vacature sluiten als vervuld?", body: "De vacature verdwijnt uit het overzicht en uit Google. Wie de oude link opent, ziet dat de vacature is vervuld.", openApplications: "Er staan nog {aantal} sollicitaties open. Die rond je zelf af.", confirm: "Sluiten als vervuld" },
    close: { title: "Vacature sluiten?", body: "Kies waarom de vacature sluit. Wie de oude link opent, ziet 30 dagen lang dat de vacature gesloten is.", reason: "Reden", confirm: "Vacature sluiten" },
    reopen: { title: "Vacature heropenen?", body: "Kies een nieuwe sluitdatum. De vacature staat daarna direct weer op de website.", closesOn: "Nieuwe sluitdatum", confirm: "Heropenen" },
    extend: { title: "Vacature verlengen?", body: "De sluitdatum schuift 30 dagen op, naar {datum}.", confirm: "30 dagen verlengen" },
    archive: { title: "Vacature archiveren?", body: "De vacature verdwijnt uit je overzicht en is niet meer te vinden op de website. Je kunt hem later terugzetten als concept.", confirm: "Archiveren" },
    delete: { title: "Concept verwijderen?", body: "Dit concept wordt definitief verwijderd. Dat kun je niet ongedaan maken.", confirm: "Verwijderen" },
    deleteBlocked: { title: "Verwijderen kan niet", body: "Op deze vacature zijn sollicitaties binnengekomen. Archiveer de vacature, dan blijft de koppeling met de sollicitaties bewaard.", confirm: "Archiveren" },
    finalStatus: { title: "Sollicitatie afronden?", body: "Na het opslaan start de bewaartermijn. Zonder toestemming verwijdert Groos Beheer de gegevens over 4 weken automatisch.", confirm: "Status opslaan" },
    spam: { title: "Markeren als spam?", body: "Het bericht verdwijnt uit je overzicht en wordt na 30 dagen automatisch verwijderd.", confirm: "Markeren als spam" },
    unsaved: { title: "Wijzigingen niet opgeslagen", body: "Je hebt wijzigingen die nog niet zijn opgeslagen. Wil je deze pagina verlaten zonder op te slaan?", confirm: "Pagina verlaten", cancel: "Blijven" },
    signOutEverywhere: { title: "Overal uitloggen?", body: "Je wordt op alle apparaten uitgelogd, ook op dit apparaat. Daarna log je opnieuw in met je wachtwoord en je code.", confirm: "Overal uitloggen" },
  },
  toasts: {
    welkom: "Je authenticator-app is gekoppeld. Welkom bij Groos Beheer.",
    wachtwoord: "Je nieuwe wachtwoord is opgeslagen.",
    opgeslagen: "De vacature is opgeslagen als concept.",
    saved: "Je wijzigingen zijn opgeslagen.",
    published: "De vacature is gepubliceerd en staat nu op de website.",
    changesPublished: "Je wijzigingen staan nu op de website.",
    savedNotPublished: "De vacature is opgeslagen, maar nog niet gepubliceerd. Vul eerst de velden in die nog ontbreken.",
    scheduled: "De vacature is ingepland en verschijnt op {datum} om {tijd}.",
    unscheduled: "De inplanning is geannuleerd. De vacature is weer een concept.",
    offline: "De vacature is offline gehaald en staat weer klaar als concept.",
    filled: "De vacature is gesloten als vervuld.",
    closed: "De vacature is gesloten.",
    reopened: "De vacature staat weer online tot {datum}.",
    extended: "De sluitdatum is verlengd tot {datum}.",
    archived: "De vacature is gearchiveerd.",
    restored: "De vacature is teruggezet als concept.",
    gedupliceerd: "Er is een kopie gemaakt. Je bewerkt nu de kopie, die nog niet online staat.",
    verwijderd: "Het concept is verwijderd.",
    featured: "De vacature is uitgelicht.",
    unfeatured: "De vacature is niet meer uitgelicht.",
    urgentOn: "Het label Spoed staat aan.",
    urgentOff: "Het label Spoed staat uit.",
    linkCopied: "De link naar de vacature is gekopieerd.",
    statusChanged: "De status is gewijzigd naar {status}.",
    assigned: "Toegewezen aan {naam}.",
    unassigned: "Niemand is nu toegewezen.",
    noteAdded: "Je notitie is toegevoegd.",
  },
  errors: {
    sessie_verlopen: "Je sessie is verlopen. Log opnieuw in om verder te gaan.",
    mfa_vereist: "Bevestig eerst je code uit de authenticator-app.",
    geen_toegang: "Dit account heeft geen toegang meer tot het beheer. Neem contact op met een eigenaar.",
    geen_rechten: "Je hebt geen rechten voor deze actie. Vraag een eigenaar om hulp.",
    ongeldig: "Niet alle velden zijn goed ingevuld. Bekijk de meldingen bij de velden.",
    niet_publiceerbaar: "De vacature is nog niet compleet. Vul de velden in die hieronder staan.",
    ongeldige_overgang: "Deze actie kan niet meer, omdat de status intussen is veranderd. De pagina is ververst.",
    niet_gevonden: "Dit onderdeel bestaat niet meer.",
    conflict: "Iemand anders heeft deze vacature intussen aangepast. Laad de pagina opnieuw en voer je wijziging nog een keer in.",
    bot: "Onze beveiliging heeft dit verzoek tegengehouden. Probeer het over een paar minuten opnieuw.",
    onbekend: "Er ging iets mis bij het opslaan. Controleer je internetverbinding en probeer het opnieuw.",
    cvFailed: "Het cv kon niet worden geopend. Probeer het opnieuw.",
    errorSummaryOne: "Eén veld is niet goed ingevuld.",
    errorSummaryMany: "Er zijn {aantal} velden niet goed ingevuld.",
  },
  validation: {
    required: "Dit veld is verplicht.",
    email: "Vul een geldig e-mailadres in, zoals naam@voorbeeld.nl.",
    otp: "Vul de zes cijfers uit je authenticator-app in.",
    titleMissing: "Vul een functietitel in.",
    titleTooLong: "Een functietitel mag hoogstens 80 tekens lang zijn. Houd hem kort, dan blijft hij leesbaar in Google.",
    occupationMissing: "Kies het beroep waar deze vacature bij hoort.",
    cityMissing: "Vul de plaats in waar het werk is.",
    postalCode: "Vul een postcode in zoals 2553 ER.",
    tooLong: "Dit veld mag hoogstens {aantal} tekens hebben.",
    listTooLong: "Een lijst mag hoogstens 10 regels hebben.",
    itemTooLong: "Een regel mag hoogstens 200 tekens hebben.",
    hoursRange: "Vul een aantal uren tussen 1 en 60 in.",
    hoursOrder: "Het minimum aantal uren is hoger dan het maximum. Controleer de uren per week.",
    salaryRange: "Vul een bruto uurloon tussen € 5,00 en € 100,00 in.",
    salaryOrder: "Het minimale uurloon is hoger dan het maximale. Controleer de bedragen.",
    positions: "Vul een aantal plekken tussen 1 en 99 in.",
    experienceMonths: "Vul een aantal maanden tussen 1 en 120 in.",
    qualificationsOverlap: "Een kwalificatie kan niet tegelijk vereist en een pré zijn.",
    minAgeReason: "Kies de reden voor de minimumleeftijd.",
    startDate: "Kies een startdatum of vink Per direct beginnen aan.",
    closesInPast: "De sluitdatum ligt in het verleden. Kies een datum na vandaag.",
    closesRequired: "Kies een sluitdatum. Bij een geplande, online of gesloten vacature kan dit veld niet leeg zijn.",
    closesBeforePublish: "De sluitdatum moet na het moment van publiceren liggen.",
    publishInPast: "Kies een moment in de toekomst om de vacature in te plannen.",
    contact: "Kies een contactpersoon.",
    noteTooShort: "Schrijf minimaal twee tekens.",
    noteTooLong: "Een notitie mag hoogstens 4000 tekens hebben.",
    belowMinimumWage: "Dit uurloon ligt onder het wettelijk minimumloon van {bedrag} per uur voor 21 jaar en ouder. Controleer het bedrag voordat je publiceert.",
    publish: {
      title: "Vul een functietitel in.",
      city: "Vul de plaats in waar het werk is.",
      hours: "Vul de uren per week in, minimaal en maximaal.",
      salary: "Vul het bruto uurloon in, vanaf en tot.",
      intro: "Schrijf een introductie van minimaal twee korte zinnen.",
      tasks: "Voeg minimaal drie taken toe bij Je werkdag.",
      requirements: "Voeg minimaal één eis toe bij Wat je meebrengt.",
      offer: "Voeg minimaal één punt toe bij Wat je van ons krijgt.",
      start: "Kies een startdatum of vink Per direct beginnen aan.",
      contact: "Kies een actieve contactpersoon.",
      publish_at: "Kies een moment in de toekomst om de vacature in te plannen.",
    },
  },
  notFound: { metaTitle: "Pagina niet gevonden", title: "Deze pagina bestaat niet", body: "De link klopt niet of het onderdeel is verwijderd.", home: "Naar het overzicht" },
  error: { metaTitle: "Er ging iets mis", title: "Er ging iets mis", body: "Deze pagina kon niet worden geladen. Probeer het opnieuw of ga terug naar het overzicht.", retry: "Opnieuw proberen", home: "Naar het overzicht", code: "Foutcode {code}" },
  more: { title: "Meer", metaTitle: "Meer" },
} as const;

export type BeheerStrings = typeof S;

/** Vervangt {naam} door values.naam; onbekende plaatshouders blijven staan. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{([a-z_]+)\}/gi, (match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : match,
  );
}
